name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Install MSYS2
        run: |
          choco install msys2 --no-progress -y

      - name: Install Cairo via MSYS2
        run: |
          C:\tools\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
          C:\tools\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-cairo"

      - name: Copy libcairo2.dll to project directory
        run: |
          Copy-Item C:\tools\msys64\mingw64\bin\libcairo-2.dll ./libcairo2.dll

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --add-binary "libcairo2.dll;." main.py

      - name: Rename executable
        run: |
          Move-Item dist\main.exe dist\raster2waves.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: raster2waves-executable
          path: dist/raster2waves.exe
